name: QA Build Test
description: Checklist for to assist in performing quality assurance checks on upcoming builds or to test resolution of issues.
title: "QA Test - [software] - [version] - [DATE]"
labels: ["anchor", "test"]
body:
  - type: markdown
    attributes:
      value: "Please make sure to edit the title with the software name, version, and date.  Thanks!"
  - type: markdown
    attributes:
      value: "# Conditions"
  - type: dropdown
    id: OS
    attributes:
      label: Platform
      description: What platform are you running Anchor on?
      options:
        - Desktop
        - iOS
        - Android
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Anchor are you using?
      placeholder: ex. 0.40.0
  - type: input
    id: device-hardware
    attributes:
      label: Device
      description: What device are you using?
      placeholder: ex. iPhone 13 or Pixel 5
  - type: input
    id: device-osversion
    attributes:
      label: Device OS Version
      description: What version of your device's OS are you using?
  - type: markdown
    attributes:
      value: "---"
  - type: markdown
    attributes:
      value: "# Build Test"
  - type: markdown
    attributes:
      value: "Please check boxes of items that were tested, regardless of outcome.  If you find an issue, please select 'See Notes' and explain the issue below"
  - type: dropdown
    id: accountcreation
    attributes:
      label: Account Creation
      options:
        - Good
        - See Notes
        - Not Tested
    validations:
      required: true
  - type: checkboxes
    id: creation
    attributes:
      label: AC Checks
      options:
        - label: Account Created
        - label: Backup Created
  - type: dropdown
    id: accountrecovery
    attributes:
      label: Account Recovery
      options:
        - Good
        - See Notes
        - Not Tested
    validations:
      required: true
  - type: checkboxes
    id: archecks
    attributes:
      label: AR Checks
      options:
        - label: Certificate Scanned
        - label: Account Recoverd
  - type: dropdown
    id: accountimport
    attributes:
      label: Account Import
      options:
        - Good
        - See Notes
        - Not Tested
    validations:
      required: true
  - type: checkboxes
    id: aichecks
    attributes:
      label: AI Checks
      options:
        - label: Key Scanned
        - label: Account Imported
  - type: checkboxes
    id: functionality
    attributes:
      label: Functionality
      description: Did the software function correctly?
      options:
        - label: Web Wallet button
        - label: Bloks.io button
        - label: Preferences
        - label: Export Key
  - type: textarea
    id: Oot
    attributes:
      label: Unique Tests
      description: Are there any specific items to test.  If so, please note them here.  If we need to test this regularly, please add it to the list above.
  - type: textarea
    attributes:
      label: Notes
      description: |
        Were there issues with any of the steps above that need attention?

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false