name: QA Build Test
description: Checklist for to assist in performing quality assurance checks on upcoming builds or to test resolution of issues.
title: "QA Test - [software] - [version] - [DATE]"
labels: ["anchor", "test"]
body:
  - type: markdown
    attributes:
      value: "# Conditions"
  - type: dropdown
    id: OS
    attributes:
      label: Platform
      description: What platform are you running Anchor on?
      options:
        - Desktop
        - iOS
        - Android
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Anchor are you using?
      placeholder: ex. 0.40.0
  - type: input
    id: device-hardware
    attributes:
      label: Device
      description: What device are you using?
      placeholder: ex. iPhone 13 or Pixel 5
  - type: input
    id: device-osversion
    attributes:
      label: Device OS Version
      description: What version of your device's OS are you using?
  - type: markdown
    attributes:
      value: "---"
  - type: markdown
    attributes:
      value: "# Build Test"
  - type: dropdown
    id: accountcreation
    attributes:
      label: Account Creation
      options:
        - Good
        - See Notes
        - Not Tested
    validations:
      required: true
  - type: checkboxes
    id: creation
    attributes:
      options:
        - label: Creation
        - label: Backup
  - type: dropdown
    id: accountrecovery
    attributes:
      label: Account Recovery
      options:
        - Good
        - See Notes
        - Not Tested
    validations:
      required: true
  - type: checkboxes
    id: archecks
    attributes:
      options:
        - label: Scanned
        - label: Account Recoverd
  - type: dropdown
    id: accountimport
    attributes:
      label: Account Import
      options:
        - Good
        - See Notes
        - Not Tested
    validations:
      required: true
  - type: checkboxes
    id: aichecks
    attributes:
      options:
        - label: Scanned
        - label: Account Imported
  - type: checkboxes
    id: functionality
    attributes:
      label: Functionality
      description: Did function correctly?
      options:
        - label: Web Wallet button
        - label: Bloks.io button
        - label: Preferences
        - label: Export Key
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Were there issues with any of the steps above that need attention?
      render: shell
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false